GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62a6e72467d0b5ed53c87f07

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Johnny Test",
    "subscribedToChannel": "My Channel"

}

###

DELETE http://localhost:3000/subscribers/62a6e72467d0b5ed53c87f07

###

PATCH  http://localhost:3000/subscribers/62a6e35c7d1524d8f9899244
Content-Type: application/json
 
 {
     "name": "Jonny Bravo"
 }